service_remediation:
  name: remediation
  python_module: saq.remediation
  python_class: RemediationService
  description: Handles requests for removing and/or restoring emails, files, accounts, etc...
  enabled: true
  instance_types: [ANY]
  max_threads: 10
  batch_size: 20
  delay_minutes: 5
  lock_timeout_seconds: 60
  request_wait_time: 20
  unchecked_types: []

analysis_module_automated_remediation:
  name: automated_remediation
  python_module: saq.modules.remediation
  python_class: AutomatedRemediationAnalyzer
  enabled: false
  valid_observable_types:
    - email_delivery
  required_directives:
    - remediate

module_group_correlation:
  modules:
    - automated_remediation

config:
  remediation_local: etc/saq.remediation.yaml