import base64
import logging

from saq.configuration.error import EncryptedPasswordError
from saq.constants import G_ENCRYPTION_KEY
from saq.environment import g

def export_encrypted_passwords():
    """Returns a JSON dict of all the encrypted passwords with decrypted values."""
    from saq.database import get_db_connection
    from saq.configuration.config import get_config
    with get_db_connection(name=get_config().global_settings.encrypted_passwords_db) as db:
        c = db.cursor()
        c.execute("""
SELECT
    `key`, `encrypted_value`
FROM
    `encrypted_passwords`
ORDER BY
    `key`""")
        export = {}
        for row in c:
            #logging.info(f"exporting password for {row[0]}")
            try:
                export[row[0]] = decrypt_password(row[0])
            except EncryptedPasswordError:
                export[row[0]] = None

        return export

def import_encrypted_passwords(export):
    """Imports the JSON dict generated by export_encrypted_passwords."""
    for key, value in export.items():
        logging.info(f"importing password for {key}")
        encrypt_password(key, value)

def encrypt_password(key, value):
    """Stores sensitive data as an encrypted value."""
    from saq.crypto import encrypt_chunk
    from saq.configuration.config import get_config
    encrypted_value = base64.b64encode(encrypt_chunk(value.encode('utf8')))

    from saq.database import get_db_connection
    with get_db_connection(name=get_config().global_settings.encrypted_passwords_db) as db:
        c = db.cursor()
        c.execute("""
INSERT INTO `encrypted_passwords` ( `key`, `encrypted_value` )
VALUES ( %s, %s )
ON DUPLICATE KEY UPDATE
    `encrypted_value` = %s""", ( key, encrypted_value, encrypted_value ))
        db.commit()

def delete_password(key):
    """Deletes the given password from the database. Returns True if the password was deleted."""
    from saq.database import get_db_connection
    from saq.configuration.config import get_config
    with get_db_connection(name=get_config().global_settings.encrypted_passwords_db) as db:
        c = db.cursor()
        c.execute("DELETE FROM `encrypted_passwords` WHERE `key` = %s", (key,))
        db.commit()
        return c.rowcount == 1

def decrypt_password(key):
    """Returns the decrypted value for the given key."""
    from saq.database import get_db_connection
    from saq.configuration.config import get_config
    with get_db_connection(name=get_config().global_settings.encrypted_passwords_db) as db:
        c = db.cursor()
        c.execute("""
SELECT 
    `encrypted_value`
FROM
    `encrypted_passwords`
WHERE
    `key` = %s
""", (key,))
        row = c.fetchone()
        if row is None:
            logging.warning(f"request for unknown encrypted password {key}")
            return None

        if g(G_ENCRYPTION_KEY):
            from saq.crypto import decrypt_chunk
            return decrypt_chunk(base64.b64decode(row[0])).decode('utf8')
        else:
            logging.error(f"request to decrypt {key} without decryption key set")
            return None
            #raise EncryptedPasswordError(key=key)
