from typing import Optional
from pydantic import BaseModel, Field

class GlobalConfig(BaseModel):
    company_name: str = Field(..., description="the default company name to use for alerts generated by engines using this configuration file")
    company_id: int = Field(..., description="the default company id to use for alerts generated by engines using this configuration file")
    instance_name: str = Field(..., description="shows up in the GUI so you know which instance you're logged into")
    node: str = Field(..., description="the name of this node, usually this is the fully qualified domain name; if this is set to AUTO then socket.getfqdn() is used")
    instance_type: str = Field(..., description="this can be either PRODUCTION, QA or DEV; used by some routines to prevent a user from making a horrible mistake")
    debug: bool = Field(..., description="forces the entire application to run under a single thread")
    data_dir: str = Field(..., description="global data directory that has all the things (relative to SAQ_HOME)")
    analyst_data_dir: str = Field(..., description="analyst data directory that has files that analysts can control through an external git repository")
    tmp_dir: Optional[str] = Field(default=None, description="if you need to override the default temp directory, set this to the path; if the path is relative, it is relative to the SAQ_HOME directory")
    error_reporting_dir: str = Field(..., description="directory that contains any stack traces for review (relative to DATA_DIR)")
    error_reporting_email: str = Field(..., description="list of email addresses (comma separated) that get these reports sent to them automatically")
    condition_reporting_delay: int = Field(..., description="the amount of time (in minutes) in between reporting of the same condition; set to 0 to disable condition reporting")
    local_domains: list[str] = Field(..., description="comma separated list of local domains")
    local_email_domains: list[str] = Field(..., description="comma separated list of valid email domains; these are domains that you receive emails for")
    log_sql: bool = Field(..., description="set to yes to log all SQL commands executed by the server")
    log_sql_exec_times: bool = Field(..., description="set to yes to log all SQL commands and their execution time")
    enable_semaphores: bool = Field(..., description="set this to True to enable semaphores; you'll definitely want this to be True in production settings")
    global_engine_instance_count: int = Field(..., description="set this to the total number of analysis engines (of any type) you have running")
    ignore_days: int = Field(..., description="the number of days alerts set to IGNORE will last until they are deleted from the system")
    fp_days: int = Field(..., description="the number of days alerts set to FALSE_POSITIVE will last until they are reset")
    distribute_days_old: int = Field(..., description="distribute old alerts that are NOT part of an event to another node after N days; set this to 0 to disable")
    distribution_target: str = Field(..., description="the node to distribute the alerts to; this will be equal to the 'node' value of this config section on the target machine")
    lock_timeout: str = Field(..., description="when alerts are being processed they are locked for processing; if a process dies during process then a stale lock could linger; the amount of time a lock is considered valid (in MM:SS format)")
    lock_keepalive_frequency: int = Field(..., description="amount of time (in seconds) between lock keep alive messages")
    maximum_cumulative_analysis_warning_time: int = Field(..., description="amount of time (in seconds) that we expect analysis to take, in general; we use this to warn ourselves that something might be wrong with logic in a module")
    maximum_cumulative_analysis_fail_time: int = Field(..., description="amount of time (in seconds) to give analysis (in total) before we bail entirely")
    maximum_analysis_time: int = Field(..., description="amount of time (in seconds) that we expect a single analysis module to take")
    check_watched_files_frequency: int = Field(..., description="how often (in seconds) modules check to see if watched files have been modified")
    memory_limit_warning: int = Field(..., description="issue a warning when a worker process uses this much memory (in MB)")
    memory_limit_kill: int = Field(..., description="kill a worker when it uses this much memory (in MB)")
    encrypted_passwords_db: str = Field(..., description="this is the name of the database configuration SECTION (database_SECTION) we use to query for encrypted passwords")
    maximum_analysis_disk_size: int = Field(..., description="maximum allowed size in bytes for an analysis (JSON + size of file observables); set this to 0 to disable this functionality")
    maximum_observable_count: int = Field(..., description="the total number of observables a single root analysis can have; once this threshold is met, no more observables can be added; set to 0 to disable this functionality")

class ServiceConfig(BaseModel):
    module: str = Field(..., description="The Python module that contains the service class.")
    class_name: str = Field(..., description="The name of the service class inside the module.", alias="class")
    description: str = Field(..., description="A brief description of the service.")
    enabled: bool = Field(..., description="Controls whether the service is enabled or disabled.")

class DatabaseConfig(BaseModel):
    hostname: str = Field(..., description="The hostname of the database server.")
    port: int = Field(..., description="The port of the database server.")
    unix_socket: Optional[str] = Field(default=None, description="(Optional) unix socket path.")
    database: str = Field(..., description="The name of the database.")
    username: str = Field(..., description="The username to use for authentication.")
    password: str = Field(..., description="The password to use for authentication.")
    ssl_ca: Optional[str] = Field(default=None, description="(Optional) The path to the SSL CA certificate.")
    ssl_key: Optional[str] = Field(default=None, description="The path to the SSL key.")
    ssl_cert: Optional[str] = Field(default=None, description="The path to the SSL certificate.")

class AnalysisModuleConfig(BaseModel):
    id: str = Field(..., description="Unique identifier for the analysis module.")
    module: str = Field(..., description="The Python module that contains the analysis module class.")
    class_name: str = Field(..., description="The name of the analysis module class inside the module.", alias="class")
    enabled: bool = Field(..., description="Controls whether the analysis module is enabled or disabled.")

class CollectionGroupConfig(BaseModel):
    enabled: bool = Field(..., description="Controls whether the collection group is enabled or disabled.")
    coverage: int = Field(..., description="The coverage (in percentage) of the collection group, ranging from 0 to 100.")
    full_delivery: bool = Field(..., description="Guarantees delivery of all submissions to this group.")
    database: str = Field(..., description="The database to use to find the target nodes to send submissions to.")
    company_id: int = Field(..., description="The company ID that the collection group belongs to.")

class AnalysisModeConfig(BaseModel):
    cleanup: bool = Field(..., description="Controls whether the analysis mode should clean up after itself.")
    module_groups: list[str] = Field(..., description="A list of module groups that the analysis mode belongs to.")
    maximum_cumulative_analysis_warning_time: int = Field(..., description="The maximum cumulative analysis warning time (in seconds).")
    maximum_cumulative_analysis_fail_time: int = Field(..., description="The maximum cumulative analysis fail time (in seconds).")
    maximum_analysis_time: int = Field(..., description="The maximum analysis time (in seconds).")

class LLMConfig(BaseModel):
    embedding_model: str = Field(..., description="the embedding model to use for vectorization")

class MonitorConfig(BaseModel):
    use_stdout: bool = Field(..., description="enable stdout monitoring")
    use_stderr: bool = Field(..., description="enable stderr monitoring")
    use_logging: bool = Field(..., description="enable logging monitoring")
    use_cache: bool = Field(..., description="enable cache monitoring")

class RabbitMQConfig(BaseModel):
    username: str = Field(..., description="rabbitmq username")
    password: str = Field(..., description="rabbitmq password")
    host: str = Field(..., description="rabbitmq host")
    port: int = Field(..., description="rabbitmq port")

class MinioConfig(BaseModel):
    host: str = Field(..., description="minio host")
    port: int = Field(..., description="minio port")
    access_key: str = Field(..., description="minio access key")
    secret_key: str = Field(..., description="minio secret key")
    secure: bool = Field(..., description="set to use SSL")
    cert_check: bool = Field(..., description="set to validate SSL certification")
    region: Optional[str] = Field(description="leave empty for MinIO server")

class RedisConfig(BaseModel):
    host: str = Field(..., description="redis host")
    port: int = Field(..., description="redis port")
    username: str = Field(..., description="redis username")
    password: str = Field(..., description="redis password")
    use_ssl: bool = Field(..., description="use SSL for redis connection")
    ssl_ca_path: Optional[str] = Field(default=None, description="path to SSL CA certificate")

class QdrantConfig(BaseModel):
    url: str = Field(..., description="qdrant URL")
    use_ssl: bool = Field(..., description="use SSL for qdrant connection")
    ssl_ca_path: str = Field(..., description="path to SSL CA certificate")
    api_key: str = Field(..., description="qdrant API key")
    collection_alerts: str = Field(..., description="the collection name for ace3 alert data")

class DatabaseConfig(BaseModel):
    max_connection_lifetime: str = Field(..., description="how long (in HH:MM:SS format) a database connection is considered valid")

class SQLite3Config(BaseModel):
    timeout: int = Field(..., description="how long (in seconds) to wait for sqlite3 to connect")

class EncryptionConfig(BaseModel):
    salt_size: int = Field(..., description="size of the salt for PBKDF2 (in bytes)")
    iterations: int = Field(..., description="iterations for the PBKDF2 algorithm")

class CollectionConfig(BaseModel):
    persistence_dir: str = Field(..., description="contains various persistent information used by collectors (relative to DATA_DIR)")
    incoming_dir: str = Field(..., description="directory for incoming submissions (relative to DATA_DIR)")
    error_dir: str = Field(..., description="contains failed submission (relative to DATA_DIR)")
    tuning_temp_dir: str = Field(..., description="path (relative to DATA_DIR) to use to store temporary file buffers for tuning")
    tuning_update_frequency: str = Field(..., description="control how often the tuning rules are checked for updates in HH:MM:SS format")
    force_api: bool = Field(..., description="set to yes to force collection to use the API even if the target node is local")

class QueryHunterConfig(BaseModel):
    max_result_count: int = Field(..., description="maximum number of results queries should return")
    query_timeout: str = Field(..., description="maximum amount of time (in HH:MM:SS format) to wait for a query to complete")

class SSLConfig(BaseModel):
    ca_chain_path: str = Field(..., description="path to SSL CA chain certificate")

class ProxyConfig(BaseModel):
    transport: str = Field(..., description="proxy transport protocol")
    host: str = Field(..., description="proxy host")
    port: str = Field(..., description="proxy port")
    user: str = Field(..., description="proxy username")
    password: str = Field(..., description="proxy password")

class APIConfig(BaseModel):
    listen_address: str = Field(..., description="binding address for incoming requests")
    listen_port: int = Field(..., description="listening port")
    ssl_cert: str = Field(..., description="path to SSL certificate")
    ssl_key: str = Field(..., description="path to SSL key")
    secret_key: str = Field(..., description="secret key for API")
    default_alert_type: str = Field(..., description="the default alert type when submissions do not include it")
    api_key: str = Field(..., description="autogenerated api key used for node-to-node communication")
    prefix: str = Field(..., description="the prefix that other systems use to connect to the API server")

class GUIConfig(BaseModel):
    listen_address: str = Field(..., description="binding address for incoming requests")
    listen_port: int = Field(..., description="listening port")
    ssl_cert: str = Field(..., description="path to SSL certificate")
    ssl_key: str = Field(..., description="path to SSL key")
    authentication: bool = Field(..., description="force users to authenticate to the gui")
    display_events: bool = Field(..., description="display events tab")
    display_metrics: bool = Field(..., description="display metrics tab")
    display_overview: bool = Field(..., description="display overview tab")
    google_analytics: bool = Field(..., description="enable Google Analytics")
    settings_import_enabled: bool = Field(..., description="allow settings to be imported")
    dispositioning: bool = Field(..., description="enable dispositioning feature")
    ownership: bool = Field(..., description="enable ownership feature")
    email_remediation: bool = Field(..., description="enable email remediation feature")
    event_management: bool = Field(..., description="enable event management feature")
    add_observable: bool = Field(..., description="enable add observable feature")
    analyze_alert: bool = Field(..., description="enable analyze alert feature")
    fp_easy_button: bool = Field(..., description="enable false positive easy button")
    ignore_easy_button: bool = Field(..., description="enable ignore easy button")
    upload_vt: bool = Field(..., description="enable VirusTotal upload")
    upload_vxstream: bool = Field(..., description="enable VxStream upload")
    view_in_vx: bool = Field(..., description="enable view in VxStream")
    clear_cloudphish_alert: bool = Field(..., description="allows analysts to clear cached URL content")
    show_total_alert_count: bool = Field(..., description="show the total alerts resulting from the current filter")
    matching_open_events_collapsed: bool = Field(..., description="default matching open events toggle position")
    alert_details_collapsed: bool = Field(..., description="default alert details toggle position")
    hide_intel: bool = Field(..., description="hide intel if we don't want to let people see it")
    base_uri: str = Field(..., description="the base address for the GUI (used to build ACE permalinks)")
    default_company_id: int = Field(..., description="default company for manual analysis")
    core_companies: list[int] = Field(..., description="define what companies are core companies")
    secret_key: str = Field(..., description="secret key used by flask")
    whitelist_excluded_observable_types: list[str] = Field(..., description="comma separated list of observable types that are excluded from whitelisting")
    file_preview_bytes: int = Field(..., description="specifies the number of bytes of read when generating previews for files")
    local_node_only: bool = Field(..., description="by default we only show alerts that exist on the local node")
    show_root_observables: bool = Field(..., description="enabling this option forces all observables in the root analysis to be visible in the critical analysis view")
    navigation_tabs: str = Field(..., description="a comma separated list of navigation tables visible from this node")

class NetworkConfigurationConfig(BaseModel):
    managed_networks: list[str] = Field(..., description="command separated list of CIDR notation for managed networks")

class WikiConfig(BaseModel):
    base_url: str = Field(..., description="base URL for wiki (designed to work with Confluence)")
    alert_reference_enabled: bool = Field(..., description="enable alert reference links to wiki documentation")
    event_link_enabled: bool = Field(..., description="enable wiki link next to event names on manage events page")

class SMTPConfig(BaseModel):
    enabled: bool = Field(..., description="enable SMTP email sending")
    server: str = Field(..., description="SMTP server address")
    mail_from: str = Field(..., description="from email address")

class MessagingConfig(BaseModel):
    lock_timeout: int = Field(..., description="how long (in seconds) a message can be locked before the lock times out")
    batch_size: int = Field(..., description="how many requests to lock for dispatch at a single time")

class EmailArchiveConfig(BaseModel):
    target: str = Field(..., description="possible values: minio, s3")
    primary: str = Field(..., description="if this system is archiving emails, this determines what section to use for the database config")
    s3_config: str = Field(..., description="controls which section of the config to use for the s3 config")
    s3_bucket: str = Field(..., description="the bucket to use for the email archive")

class MemcachedConfig(BaseModel):
    client_address: str = Field(..., description="the address of the memcached system used by ACE")

class EmailConfig(BaseModel):
    email_dir: str = Field(..., description="the directory that contains the emails received by ACE for scanning (relative to DATA_DIR)")
    subdir_format: str = Field(..., description="the strftime format used to generate the subdirectory names that actually contain the emails")

class LDAPConfig(BaseModel):
    ldap_server: str = Field(..., description="the LDAP server (probably your domain controller)")
    ldap_port: int = Field(..., description="the port the LDAP server listens to")
    ldap_bind_user: str = Field(..., description="user account to use for authentication")
    ldap_bind_password: str = Field(..., description="LDAP password")
    ldap_base_dn: str = Field(..., description="the base DN for searching")
    top_user: str = Field(..., description="a user is tagged as executive if they are within 2 managers of this user")

class SplunkLoggingConfig(BaseModel):
    splunk_log_dir: str = Field(..., description="location of generated splunk logs (relative to DATA_DIR)")

class SIPConfig(BaseModel):
    enabled: bool = Field(..., description="enable SIP integration")
    remote_address: str = Field(..., description="SIP remote address")
    api_key: str = Field(..., description="SIP API key")
    cache_db_path: str = Field(..., description="path to SIP cache database")

class YaraExportConfig(BaseModel):
    export_list: list[str] = Field(..., description="list of for_detect observables types to export to yara rules")
    export_template_dir: str = Field(..., description="directory of template files (relative to ANALYST_DATA_DIR)")
    export_minimum_length: int = Field(..., description="minimum length of an indicator value that would go into a yara rule")
    max_strings_per_rule: int = Field(..., description="max number of strings to allow in a yara rule")

class SIPYaraExportConfig(BaseModel):
    export_list: list[str] = Field(..., description="list of sip indicator types to export to yara rules")
    export_sources_include: str = Field(..., description="list of sources to include (defaults to all sources if left empty)")
    export_sources_exclude: str = Field(..., description="list of sources to exclude (defaults to none if left empty)")
    export_template_dir: str = Field(..., description="directory of template files")
    export_minimum_length: int = Field(..., description="minimum length of an indicator value that would go into a yara rule")

class MaliciousFilesConfig(BaseModel):
    malicious_dir: str = Field(..., description="directory where malicious files are stored")
    malicious_alert_recipients: str = Field(..., description="comma separated list of email accounts to send notifications to when new files are added")

class CustomAlertsConfig(BaseModel):
    template_dir: str = Field(..., description="directory containing all flask views")
    dir: str = Field(..., description="semicolon-separated list of dirs containing all custom alert views")

class DomainGenerationConfig(BaseModel):
    keyword_file_path: str = Field(..., description="path to keyword file (relative to ANALYST_DATA_DIR)")
    opensquat: str = Field(..., description="relative path to the opensquat external tool")
    static_domain_file: str = Field(..., description="path to static domains file (relative to ANALYST_DATA_DIR)")

class SettingsConfig(BaseModel):
    refresh_seconds: int = Field(..., description="how often to refresh settings (in seconds)")

class ObservableExpirationMappingsConfig(BaseModel):
    never_expire_with_threat_actor: bool = Field(..., description="set any observables expires_on value to Null (never expire) if the observable is inside an event that has a threat actor assigned to it")

class EventsConfig(BaseModel):
    closed_status: str = Field(..., description="the event status that you use to indicate that the event is closed or fully processed")
    autoclose_path: str = Field(..., description="file name that contains the autoclose criteria (path is relative to ANALYST_DATA_DIR)")

class TimelineConfig(BaseModel):
    timezone: str = Field(..., description="timezone for timeline display")

class ConfigConfig(BaseModel):
    git_repos_default: str = Field(..., description="path to default git repos configuration")
    signatures_default: str = Field(..., description="path to default signatures configuration")
    zeek_default: str = Field(..., description="path to default zeek configuration")
    remediation_default: str = Field(..., description="path to default remediation configuration")
    shodan_default: str = Field(..., description="path to default shodan configuration")
    splunk_default: str = Field(..., description="path to default splunk configuration")

class ACEConfig(BaseModel):
    global_settings: GlobalConfig = Field(alias="global")
    llm: Optional[LLMConfig] = None
    monitor: Optional[MonitorConfig] = None
    rabbitmq: Optional[RabbitMQConfig] = None
    minio: Optional[MinioConfig] = None
    redis: Optional[RedisConfig] = None
    redis_local: Optional[RedisConfig] = Field(default=None, alias="redis-local")
    qdrant: Optional[QdrantConfig] = None
    database: Optional[DatabaseConfig] = None
    sqlite3: Optional[SQLite3Config] = None
    encryption: Optional[EncryptionConfig] = None
    collection: Optional[CollectionConfig] = None
    query_hunter: Optional[QueryHunterConfig] = None
    node_translation: Optional[dict[str, str]] = None
    node_translation_gui: Optional[dict[str, str]] = None
    SSL: Optional[SSLConfig] = None
    proxy: Optional[ProxyConfig] = None
    api: Optional[APIConfig] = None
    apikeys: Optional[dict[str, str]] = None
    gui: Optional[GUIConfig] = None
    gui_favicons: Optional[dict[str, str]] = None
    network_configuration: Optional[NetworkConfigurationConfig] = None
    wiki: Optional[WikiConfig] = None
    smtp: Optional[SMTPConfig] = None
    messaging: Optional[MessagingConfig] = None
    message_routing: Optional[dict] = None
    email_archive: Optional[EmailArchiveConfig] = None
    memcached: Optional[MemcachedConfig] = None
    email: Optional[EmailConfig] = None
    ldap: Optional[LDAPConfig] = None
    splunk_logging: Optional[SplunkLoggingConfig] = None
    sip: Optional[SIPConfig] = None
    yara_export: Optional[YaraExportConfig] = None
    yara_export_string_modifiers: Optional[dict[str, str]] = None
    sip_yara_export: Optional[SIPYaraExportConfig] = None
    sip_yara_export_string_modifiers: Optional[dict[str, str]] = None
    sip_indicator_type_mapping: Optional[dict[str, str]] = None
    sip_observable_type_mappping: Optional[dict[str, str]] = None
    malicious_files: Optional[MaliciousFilesConfig] = None
    observable_exclusions: Optional[dict[str, str]] = None
    custom_alerts: Optional[CustomAlertsConfig] = None
    custom_alerts_backward_compatibility: Optional[dict[str, str]] = None
    disabled_modules: Optional[dict] = None
    tags: Optional[dict[str, str]] = None
    tag_css_class: Optional[dict[str, str]] = None
    domain_generation: Optional[DomainGenerationConfig] = None
    settings: Optional[SettingsConfig] = None
    observable_expiration_mappings: Optional[ObservableExpirationMappingsConfig] = None
    events: Optional[EventsConfig] = None
    timeline: Optional[TimelineConfig] = None
    valid_dispositions: Optional[dict[str, bool]] = None
    disposition_rank: Optional[dict[str, int]] = None
    disposition_css: Optional[dict[str, str]] = None
    show_save_to_event: Optional[dict[str, bool]] = None
    benign_dispositions: Optional[dict[str, bool]] = None
    malicious_dispositions: Optional[dict[str, bool]] = None
    config: Optional[ConfigConfig] = None