service:
  flush: 1
  daemon: off
  log_level: debug

  # HTTP server useful for health/metrics while testing
  # http_server: on
  # http_listen: 0.0.0.0
  # http_port: 2020

parsers:
  - name: ace_json
    format: json
    time_key: asctime
    time_format: "%Y-%m-%d %H:%M:%S,%L"
    time_keep: true

  - name: phishfinder_json
    format: json
    time_key: date
    time_format: "%Y-%m-%d %H:%M:%S.%L %z"
    time_keep: true

  - name: mysql
    format: regex
    regex: '^(?<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z) (?<level>[0-9]+) \[(?<category>[^\]]+)\] \[(?<code>[^\]]+)\] \[(?<source>[^\]]+)\] (?<message>.*)$'
    time_key: timestamp
    time_format: "%Y-%m-%dT%H:%M:%S.%LZ"
    time_keep: true

  - name: qdrant
    format: regex
    regex: '^(?<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z)\s+(?<level>[A-Z]+)\s+(?<log_source>[^\s]+)\s+(?<message>.*)$'
    time_key: timestamp
    time_format: "%Y-%m-%dT%H:%M:%S.%LZ"
    time_keep: true

  - name: nginx
    format: regex
    regex: '^(?<time>\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2}) \[(?<level>\w+)\] (?<pid>\d+)#(?<tid>\d+): (?<message>.*)$'
    time_key: time
    time_format: "%Y/%m/%d %H:%M:%S"
    time_keep: true

  - name: redis
    format: regex
    regex: '^(?<pid>\d+):(?<role>[A-Z])\s+(?<timestamp>\d{2} \w{3} \d{4} \d{2}:\d{2}:\d{2}\.\d+)\s+(?<level>[*#\-\.])\s+(?<message>.*)$'
    time_key: timestamp
    time_format: "%d %b %Y %H:%M:%S.%L"
    time_keep: true

  - name: rabbitmq
    format: json
    time_key: time
    time_format: epoch_usecs
    time_keep: true

  - name: phishkit
    format: regex
    regex: '^\[(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}): (?<level>[A-Z]+)\/(?<process>[^\]]+)\] (?<message>.*)$'
    time_key: timestamp
    time_format: "%Y-%m-%d %H:%M:%S,%L"
    time_keep: true

pipeline:
  inputs:
    - name: forward
      listen: 0.0.0.0
      port: 24224

  filters:
    - name: parser
      match: ace-*
      key_name: log
      parser: ace_json
      reserve_data: on

    - name: parser
      match: phishfinder-*
      key_name: log
      parser: phishfinder_json
      reserve_data: on

    - name: parser
      match: mysql-db-*
      key_name: log
      parser: mysql
      reserve_data: on

    - name: parser
      match: qdrant
      key_name: log
      parser: qdrant
      reserve_data: on

    - name: parser
      match: nginx
      key_name: log
      parser: nginx
      reserve_data: on

    - name: parser
      match: redis
      key_name: log
      parser: redis
      reserve_data: on

    - name: parser
      match: rabbitmq
      key_name: log
      parser: rabbitmq
      reserve_data: on

    - name: parser
      match: phishkit
      key_name: log
      parser: phishkit
      reserve_data: on

  outputs:
    - name: file
      path: /data/logs
      match: "ace-*"
      format: template
      template: '[{asctime}] [{filename}:{lineno}] [{threadName}] [{process}] [{severity}] - {message}'
      workers: 1

    - name: file
      path: /data/logs
      match: "mysql-db-*"
      format: out_file
      workers: 1

    - name: file
      path: /data/logs
      match: "qdrant"
      format: out_file
      workers: 1

    - name: file
      path: /data/logs
      match: "nginx"
      format: out_file
      workers: 1

    - name: file
      path: /data/logs
      match: "redis"
      format: out_file
      workers: 1

    - name: file
      path: /data/logs
      match: "rabbitmq"
      format: out_file
      workers: 1

    - name: file
      path: /data/logs
      match: "garagehq"
      format: out_file
      workers: 1

    - name: file
      path: /data/logs
      match: "phishkit"
      format: out_file
      workers: 1

    - name: file
      path: /data/logs
      match: "phishfinder-*"
      format: out_file
      workers: 1
